--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 17.0

-- Started on 2025-08-14 16:42:52 CEST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 285 (class 1259 OID 17718)
-- Name: CardinalSymptoms; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CardinalSymptoms" (
    cs_id bigint NOT NULL,
    cs_key text NOT NULL,
    cs_data jsonb
);


ALTER TABLE public."CardinalSymptoms" OWNER TO postgres;

--
-- TOC entry 286 (class 1259 OID 17723)
-- Name: CardinalSymptoms_cs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."CardinalSymptoms" ALTER COLUMN cs_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CardinalSymptoms_cs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 287 (class 1259 OID 17724)
-- Name: CaseTemplates; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CaseTemplates" (
    case_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    case_data jsonb NOT NULL,
    internal_name text,
    internal_comment text
);


ALTER TABLE public."CaseTemplates" OWNER TO postgres;

--
-- TOC entry 288 (class 1259 OID 17730)
-- Name: CaseBase_case_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."CaseTemplates" ALTER COLUMN case_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CaseBase_case_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 289 (class 1259 OID 17731)
-- Name: FindingsTemplate; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."FindingsTemplate" (
    id bigint NOT NULL,
    request_group text NOT NULL,
    request_item text NOT NULL,
    request_type text,
    template text NOT NULL,
    vars jsonb NOT NULL,
    vars_path jsonb,
    title text DEFAULT ''::text
);


ALTER TABLE public."FindingsTemplate" OWNER TO postgres;

--
-- TOC entry 290 (class 1259 OID 17737)
-- Name: FindingsTemplate_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."FindingsTemplate" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."FindingsTemplate_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 291 (class 1259 OID 17738)
-- Name: PatBase; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PatBase" (
    pat_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    pat_data jsonb NOT NULL,
    case_id bigint,
    requested_at bigint,
    "userId" text
);


ALTER TABLE public."PatBase" OWNER TO postgres;

--
-- TOC entry 292 (class 1259 OID 17744)
-- Name: PatBase_pat_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PatBase" ALTER COLUMN pat_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PatBase_pat_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 293 (class 1259 OID 17745)
-- Name: PatChat; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PatChat" (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    pat_id bigint NOT NULL,
    content text,
    instance numeric DEFAULT '0'::numeric NOT NULL,
    role text DEFAULT ''::text,
    type text DEFAULT 'text'::text,
    audio_url text,
    audio_id text,
    audio_base64 text
);


ALTER TABLE public."PatChat" OWNER TO postgres;

--
-- TOC entry 294 (class 1259 OID 17754)
-- Name: PatChat_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PatChat" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PatChat_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 295 (class 1259 OID 17755)
-- Name: PatDiagnosis; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PatDiagnosis" (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    pat_id bigint,
    diagnosis_id bigint
);


ALTER TABLE public."PatDiagnosis" OWNER TO postgres;

--
-- TOC entry 296 (class 1259 OID 17759)
-- Name: PatDiagnosis_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PatDiagnosis" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PatDiagnosis_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 297 (class 1259 OID 17760)
-- Name: PatFindings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PatFindings" (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    pat_id bigint NOT NULL,
    date timestamp with time zone DEFAULT now() NOT NULL,
    data jsonb NOT NULL,
    request_id bigint,
    request_group text,
    request_item text,
    request_type text
);


ALTER TABLE public."PatFindings" OWNER TO postgres;

--
-- TOC entry 298 (class 1259 OID 17767)
-- Name: PatFindings_findings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PatFindings" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PatFindings_findings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 299 (class 1259 OID 17768)
-- Name: PatReports; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PatReports" (
    report_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    pat_id bigint NOT NULL,
    report_info jsonb NOT NULL
);


ALTER TABLE public."PatReports" OWNER TO postgres;

--
-- TOC entry 300 (class 1259 OID 17774)
-- Name: PatReports_report_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PatReports" ALTER COLUMN report_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PatReports_report_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 301 (class 1259 OID 17775)
-- Name: PatRx; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PatRx" (
    rx_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    "rx_key-0" bigint,
    "data-0" jsonb,
    "rx_key-1" bigint,
    "data-1" jsonb,
    "rx_key-2" bigint,
    "data-2" jsonb,
    pat_id bigint
);


ALTER TABLE public."PatRx" OWNER TO postgres;

--
-- TOC entry 302 (class 1259 OID 17781)
-- Name: PatRxSingle_Rx_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PatRx" ALTER COLUMN rx_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PatRxSingle_Rx_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 303 (class 1259 OID 17782)
-- Name: all_cardinal_symptoms; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.all_cardinal_symptoms AS
 SELECT DISTINCT cs.cs_id,
    cs.cs_data,
    cb.cardinal_symptom AS cs_key
   FROM (( SELECT DISTINCT jsonb_array_elements_text(("CaseTemplates".case_data -> 'cardinal_symptoms'::text)) AS cardinal_symptom
           FROM public."CaseTemplates") cb
     LEFT JOIN public."CardinalSymptoms" cs ON ((cs.cs_key = cb.cardinal_symptom)));


ALTER VIEW public.all_cardinal_symptoms OWNER TO postgres;

--
-- TOC entry 316 (class 1259 OID 37113)
-- Name: classroom_cases; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.classroom_cases (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    classroom bigint,
    case_id bigint,
    internal_name text,
    internal_comment text
);


ALTER TABLE public.classroom_cases OWNER TO postgres;

--
-- TOC entry 318 (class 1259 OID 37133)
-- Name: classroom_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.classroom_users (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    classroom bigint,
    userid text
);


ALTER TABLE public.classroom_users OWNER TO postgres;

--
-- TOC entry 319 (class 1259 OID 37136)
-- Name: classroom_users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.classroom_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.classroom_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 314 (class 1259 OID 37101)
-- Name: classrooms; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.classrooms (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text NOT NULL,
    "default" boolean DEFAULT false NOT NULL
);


ALTER TABLE public.classrooms OWNER TO postgres;

--
-- TOC entry 317 (class 1259 OID 37116)
-- Name: classrooms_cases_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.classroom_cases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.classrooms_cases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 315 (class 1259 OID 37104)
-- Name: classrooms_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.classrooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.classrooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 322 (class 1259 OID 53903)
-- Name: ref_icd; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ref_icd (
    id bigint NOT NULL,
    primary1 text,
    text text,
    conc text GENERATED ALWAYS AS (((primary1 || ' '::text) || text)) STORED,
    fts tsvector GENERATED ALWAYS AS (to_tsvector('german'::regconfig, ((primary1 || ' '::text) || text))) STORED
);


ALTER TABLE public.ref_icd OWNER TO postgres;

--
-- TOC entry 323 (class 1259 OID 53906)
-- Name: ref_icd_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ref_icd ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ref_icd_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 320 (class 1259 OID 53880)
-- Name: ref_rx; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ref_rx (
    id bigint NOT NULL,
    ppn bigint,
    count_substances bigint,
    name_strength text,
    adm_short text,
    adm_long text,
    adm_detail text
);


ALTER TABLE public.ref_rx OWNER TO postgres;

--
-- TOC entry 321 (class 1259 OID 53883)
-- Name: ref_rx_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ref_rx ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ref_rx_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3785 (class 2606 OID 17904)
-- Name: CardinalSymptoms CardinalSymptoms_cs_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CardinalSymptoms"
    ADD CONSTRAINT "CardinalSymptoms_cs_key_key" UNIQUE (cs_key);


--
-- TOC entry 3787 (class 2606 OID 17906)
-- Name: CardinalSymptoms CardinalSymptoms_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CardinalSymptoms"
    ADD CONSTRAINT "CardinalSymptoms_pkey" PRIMARY KEY (cs_id);


--
-- TOC entry 3789 (class 2606 OID 17908)
-- Name: CaseTemplates CaseBase_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CaseTemplates"
    ADD CONSTRAINT "CaseBase_pkey" PRIMARY KEY (case_id);


--
-- TOC entry 3791 (class 2606 OID 17910)
-- Name: FindingsTemplate FindingsTemplate_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."FindingsTemplate"
    ADD CONSTRAINT "FindingsTemplate_pkey" PRIMARY KEY (id);


--
-- TOC entry 3793 (class 2606 OID 17912)
-- Name: PatBase PatBase_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatBase"
    ADD CONSTRAINT "PatBase_pkey" PRIMARY KEY (pat_id);


--
-- TOC entry 3795 (class 2606 OID 17914)
-- Name: PatChat PatChat_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatChat"
    ADD CONSTRAINT "PatChat_pkey" PRIMARY KEY (id);


--
-- TOC entry 3797 (class 2606 OID 17916)
-- Name: PatDiagnosis PatDiagnosis_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatDiagnosis"
    ADD CONSTRAINT "PatDiagnosis_pkey" PRIMARY KEY (id);


--
-- TOC entry 3801 (class 2606 OID 17918)
-- Name: PatFindings PatFindings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatFindings"
    ADD CONSTRAINT "PatFindings_pkey" PRIMARY KEY (id);


--
-- TOC entry 3803 (class 2606 OID 17920)
-- Name: PatReports PatReports_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatReports"
    ADD CONSTRAINT "PatReports_pkey" PRIMARY KEY (report_id);


--
-- TOC entry 3805 (class 2606 OID 17922)
-- Name: PatRx PatRx_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatRx"
    ADD CONSTRAINT "PatRx_pkey" PRIMARY KEY (rx_id);


--
-- TOC entry 3811 (class 2606 OID 37144)
-- Name: classroom_users classroom_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.classroom_users
    ADD CONSTRAINT classroom_users_pkey PRIMARY KEY (id);


--
-- TOC entry 3809 (class 2606 OID 37122)
-- Name: classroom_cases classrooms_cases_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.classroom_cases
    ADD CONSTRAINT classrooms_cases_pkey PRIMARY KEY (id);


--
-- TOC entry 3807 (class 2606 OID 37112)
-- Name: classrooms classrooms_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.classrooms
    ADD CONSTRAINT classrooms_pkey PRIMARY KEY (id);


--
-- TOC entry 3815 (class 2606 OID 53913)
-- Name: ref_icd ref_icd_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ref_icd
    ADD CONSTRAINT ref_icd_pkey PRIMARY KEY (id);


--
-- TOC entry 3813 (class 2606 OID 53890)
-- Name: ref_rx ref_rx_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ref_rx
    ADD CONSTRAINT ref_rx_pkey PRIMARY KEY (id);


--
-- TOC entry 3799 (class 2606 OID 17934)
-- Name: PatDiagnosis unique_diagnosis_pat; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatDiagnosis"
    ADD CONSTRAINT unique_diagnosis_pat UNIQUE (diagnosis_id, pat_id);


--
-- TOC entry 3816 (class 2606 OID 18056)
-- Name: PatBase PatBase_case_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatBase"
    ADD CONSTRAINT "PatBase_case_id_fkey" FOREIGN KEY (case_id) REFERENCES public."CaseTemplates"(case_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3817 (class 2606 OID 18061)
-- Name: PatChat PatChat_pat_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatChat"
    ADD CONSTRAINT "PatChat_pat_id_fkey" FOREIGN KEY (pat_id) REFERENCES public."PatBase"(pat_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3818 (class 2606 OID 54496)
-- Name: PatDiagnosis PatDiagnosis_diagnosis_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatDiagnosis"
    ADD CONSTRAINT "PatDiagnosis_diagnosis_id_fkey" FOREIGN KEY (diagnosis_id) REFERENCES public.ref_icd(id);


--
-- TOC entry 3819 (class 2606 OID 18071)
-- Name: PatDiagnosis PatDiagnosis_pat_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatDiagnosis"
    ADD CONSTRAINT "PatDiagnosis_pat_id_fkey" FOREIGN KEY (pat_id) REFERENCES public."PatBase"(pat_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3820 (class 2606 OID 18076)
-- Name: PatFindings PatFindings_pat_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatFindings"
    ADD CONSTRAINT "PatFindings_pat_id_fkey" FOREIGN KEY (pat_id) REFERENCES public."PatBase"(pat_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3821 (class 2606 OID 18081)
-- Name: PatReports PatReports_pat_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatReports"
    ADD CONSTRAINT "PatReports_pat_id_fkey" FOREIGN KEY (pat_id) REFERENCES public."PatBase"(pat_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3822 (class 2606 OID 18101)
-- Name: PatRx PatRx_pat_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatRx"
    ADD CONSTRAINT "PatRx_pat_id_fkey" FOREIGN KEY (pat_id) REFERENCES public."PatBase"(pat_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3823 (class 2606 OID 54503)
-- Name: PatRx PatRx_rx_key-0_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatRx"
    ADD CONSTRAINT "PatRx_rx_key-0_fkey" FOREIGN KEY ("rx_key-0") REFERENCES public.ref_rx(id);


--
-- TOC entry 3824 (class 2606 OID 54508)
-- Name: PatRx PatRx_rx_key-1_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatRx"
    ADD CONSTRAINT "PatRx_rx_key-1_fkey" FOREIGN KEY ("rx_key-1") REFERENCES public.ref_rx(id);


--
-- TOC entry 3825 (class 2606 OID 54513)
-- Name: PatRx PatRx_rx_key-2_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatRx"
    ADD CONSTRAINT "PatRx_rx_key-2_fkey" FOREIGN KEY ("rx_key-2") REFERENCES public.ref_rx(id);


--
-- TOC entry 3828 (class 2606 OID 37145)
-- Name: classroom_users classroom_users_classroom_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.classroom_users
    ADD CONSTRAINT classroom_users_classroom_fkey FOREIGN KEY (classroom) REFERENCES public.classrooms(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3826 (class 2606 OID 37128)
-- Name: classroom_cases classrooms_cases_case_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.classroom_cases
    ADD CONSTRAINT classrooms_cases_case_fkey FOREIGN KEY (case_id) REFERENCES public."CaseTemplates"(case_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3827 (class 2606 OID 37123)
-- Name: classroom_cases classrooms_cases_classroom_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.classroom_cases
    ADD CONSTRAINT classrooms_cases_classroom_fkey FOREIGN KEY (classroom) REFERENCES public.classrooms(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3979 (class 0 OID 17718)
-- Dependencies: 285
-- Name: CardinalSymptoms; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."CardinalSymptoms" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3980 (class 0 OID 17724)
-- Dependencies: 287
-- Name: CaseTemplates; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."CaseTemplates" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3993 (class 3256 OID 18136)
-- Name: CaseTemplates Enable read access for all users; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable read access for all users" ON public."CaseTemplates" FOR SELECT USING (true);


--
-- TOC entry 3994 (class 3256 OID 18137)
-- Name: PatBase Enable read access for all users; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable read access for all users" ON public."PatBase" FOR SELECT USING (true);


--
-- TOC entry 3995 (class 3256 OID 18138)
-- Name: PatFindings Enable read access for all users; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable read access for all users" ON public."PatFindings" FOR SELECT USING (true);


--
-- TOC entry 3996 (class 3256 OID 18139)
-- Name: PatReports Enable read access for all users; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable read access for all users" ON public."PatReports" FOR SELECT USING (true);


--
-- TOC entry 3981 (class 0 OID 17731)
-- Dependencies: 289
-- Name: FindingsTemplate; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."FindingsTemplate" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3982 (class 0 OID 17738)
-- Dependencies: 291
-- Name: PatBase; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."PatBase" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3983 (class 0 OID 17745)
-- Dependencies: 293
-- Name: PatChat; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."PatChat" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3984 (class 0 OID 17755)
-- Dependencies: 295
-- Name: PatDiagnosis; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."PatDiagnosis" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3985 (class 0 OID 17760)
-- Dependencies: 297
-- Name: PatFindings; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."PatFindings" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3986 (class 0 OID 17768)
-- Dependencies: 299
-- Name: PatReports; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."PatReports" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3987 (class 0 OID 17775)
-- Dependencies: 301
-- Name: PatRx; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."PatRx" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3989 (class 0 OID 37113)
-- Dependencies: 316
-- Name: classroom_cases; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.classroom_cases ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3990 (class 0 OID 37133)
-- Dependencies: 318
-- Name: classroom_users; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.classroom_users ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3988 (class 0 OID 37101)
-- Dependencies: 314
-- Name: classrooms; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.classrooms ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3992 (class 0 OID 53903)
-- Dependencies: 322
-- Name: ref_icd; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.ref_icd ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3991 (class 0 OID 53880)
-- Dependencies: 320
-- Name: ref_rx; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.ref_rx ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 4003 (class 0 OID 0)
-- Dependencies: 285
-- Name: TABLE "CardinalSymptoms"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."CardinalSymptoms" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."CardinalSymptoms" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."CardinalSymptoms" TO service_role;


--
-- TOC entry 4004 (class 0 OID 0)
-- Dependencies: 286
-- Name: SEQUENCE "CardinalSymptoms_cs_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."CardinalSymptoms_cs_id_seq" TO anon;
GRANT ALL ON SEQUENCE public."CardinalSymptoms_cs_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."CardinalSymptoms_cs_id_seq" TO service_role;


--
-- TOC entry 4005 (class 0 OID 0)
-- Dependencies: 287
-- Name: TABLE "CaseTemplates"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."CaseTemplates" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."CaseTemplates" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."CaseTemplates" TO service_role;


--
-- TOC entry 4006 (class 0 OID 0)
-- Dependencies: 288
-- Name: SEQUENCE "CaseBase_case_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."CaseBase_case_id_seq" TO anon;
GRANT ALL ON SEQUENCE public."CaseBase_case_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."CaseBase_case_id_seq" TO service_role;


--
-- TOC entry 4007 (class 0 OID 0)
-- Dependencies: 289
-- Name: TABLE "FindingsTemplate"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."FindingsTemplate" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."FindingsTemplate" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."FindingsTemplate" TO service_role;


--
-- TOC entry 4008 (class 0 OID 0)
-- Dependencies: 290
-- Name: SEQUENCE "FindingsTemplate_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."FindingsTemplate_id_seq" TO anon;
GRANT ALL ON SEQUENCE public."FindingsTemplate_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."FindingsTemplate_id_seq" TO service_role;


--
-- TOC entry 4009 (class 0 OID 0)
-- Dependencies: 291
-- Name: TABLE "PatBase"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."PatBase" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."PatBase" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."PatBase" TO service_role;


--
-- TOC entry 4010 (class 0 OID 0)
-- Dependencies: 292
-- Name: SEQUENCE "PatBase_pat_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."PatBase_pat_id_seq" TO anon;
GRANT ALL ON SEQUENCE public."PatBase_pat_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."PatBase_pat_id_seq" TO service_role;


--
-- TOC entry 4011 (class 0 OID 0)
-- Dependencies: 293
-- Name: TABLE "PatChat"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."PatChat" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."PatChat" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."PatChat" TO service_role;


--
-- TOC entry 4012 (class 0 OID 0)
-- Dependencies: 294
-- Name: SEQUENCE "PatChat_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."PatChat_id_seq" TO anon;
GRANT ALL ON SEQUENCE public."PatChat_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."PatChat_id_seq" TO service_role;


--
-- TOC entry 4013 (class 0 OID 0)
-- Dependencies: 295
-- Name: TABLE "PatDiagnosis"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."PatDiagnosis" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."PatDiagnosis" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."PatDiagnosis" TO service_role;


--
-- TOC entry 4014 (class 0 OID 0)
-- Dependencies: 296
-- Name: SEQUENCE "PatDiagnosis_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."PatDiagnosis_id_seq" TO anon;
GRANT ALL ON SEQUENCE public."PatDiagnosis_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."PatDiagnosis_id_seq" TO service_role;


--
-- TOC entry 4015 (class 0 OID 0)
-- Dependencies: 297
-- Name: TABLE "PatFindings"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."PatFindings" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."PatFindings" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."PatFindings" TO service_role;


--
-- TOC entry 4016 (class 0 OID 0)
-- Dependencies: 298
-- Name: SEQUENCE "PatFindings_findings_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."PatFindings_findings_id_seq" TO anon;
GRANT ALL ON SEQUENCE public."PatFindings_findings_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."PatFindings_findings_id_seq" TO service_role;


--
-- TOC entry 4017 (class 0 OID 0)
-- Dependencies: 299
-- Name: TABLE "PatReports"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."PatReports" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."PatReports" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."PatReports" TO service_role;


--
-- TOC entry 4018 (class 0 OID 0)
-- Dependencies: 300
-- Name: SEQUENCE "PatReports_report_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."PatReports_report_id_seq" TO anon;
GRANT ALL ON SEQUENCE public."PatReports_report_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."PatReports_report_id_seq" TO service_role;


--
-- TOC entry 4019 (class 0 OID 0)
-- Dependencies: 301
-- Name: TABLE "PatRx"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."PatRx" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."PatRx" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."PatRx" TO service_role;


--
-- TOC entry 4020 (class 0 OID 0)
-- Dependencies: 302
-- Name: SEQUENCE "PatRxSingle_Rx_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."PatRxSingle_Rx_id_seq" TO anon;
GRANT ALL ON SEQUENCE public."PatRxSingle_Rx_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."PatRxSingle_Rx_id_seq" TO service_role;


--
-- TOC entry 4021 (class 0 OID 0)
-- Dependencies: 303
-- Name: TABLE all_cardinal_symptoms; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.all_cardinal_symptoms TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.all_cardinal_symptoms TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.all_cardinal_symptoms TO service_role;


--
-- TOC entry 4022 (class 0 OID 0)
-- Dependencies: 316
-- Name: TABLE classroom_cases; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.classroom_cases TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.classroom_cases TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.classroom_cases TO service_role;


--
-- TOC entry 4023 (class 0 OID 0)
-- Dependencies: 318
-- Name: TABLE classroom_users; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.classroom_users TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.classroom_users TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.classroom_users TO service_role;


--
-- TOC entry 4024 (class 0 OID 0)
-- Dependencies: 319
-- Name: SEQUENCE classroom_users_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.classroom_users_id_seq TO anon;
GRANT ALL ON SEQUENCE public.classroom_users_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.classroom_users_id_seq TO service_role;


--
-- TOC entry 4025 (class 0 OID 0)
-- Dependencies: 314
-- Name: TABLE classrooms; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.classrooms TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.classrooms TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.classrooms TO service_role;


--
-- TOC entry 4026 (class 0 OID 0)
-- Dependencies: 317
-- Name: SEQUENCE classrooms_cases_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.classrooms_cases_id_seq TO anon;
GRANT ALL ON SEQUENCE public.classrooms_cases_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.classrooms_cases_id_seq TO service_role;


--
-- TOC entry 4027 (class 0 OID 0)
-- Dependencies: 315
-- Name: SEQUENCE classrooms_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.classrooms_id_seq TO anon;
GRANT ALL ON SEQUENCE public.classrooms_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.classrooms_id_seq TO service_role;


--
-- TOC entry 4028 (class 0 OID 0)
-- Dependencies: 322
-- Name: TABLE ref_icd; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.ref_icd TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.ref_icd TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.ref_icd TO service_role;


--
-- TOC entry 4029 (class 0 OID 0)
-- Dependencies: 323
-- Name: SEQUENCE ref_icd_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.ref_icd_id_seq TO anon;
GRANT ALL ON SEQUENCE public.ref_icd_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.ref_icd_id_seq TO service_role;


--
-- TOC entry 4030 (class 0 OID 0)
-- Dependencies: 320
-- Name: TABLE ref_rx; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.ref_rx TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.ref_rx TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.ref_rx TO service_role;


--
-- TOC entry 4031 (class 0 OID 0)
-- Dependencies: 321
-- Name: SEQUENCE ref_rx_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.ref_rx_id_seq TO anon;
GRANT ALL ON SEQUENCE public.ref_rx_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.ref_rx_id_seq TO service_role;


-- Completed on 2025-08-14 16:42:54 CEST

--
-- PostgreSQL database dump complete
--

CREATE VIEW all_cardinal_symptoms AS
SELECT DISTINCT 
    cs.cs_id AS cs_id,
    cs.cs_data AS cs_data,
    cb.cardinal_symptom AS cs_key
FROM (
    SELECT DISTINCT jsonb_array_elements_text(case_data->'cardinal_symptoms') AS cardinal_symptom
    FROM "CaseTemplates"
) cb
LEFT JOIN "CardinalSymptoms" cs
ON cs.cs_key = cb.cardinal_symptom;

CREATE OR REPLACE FUNCTION public.append_lab_results(
  input_pat_id INTEGER,
  input_userId TEXT,
  new_lab_result JSONB
)
RETURNS VOID AS $$
BEGIN
  -- Check if a lab entry with the same created_at timestamp already exists
  IF NOT EXISTS (
    SELECT 1
    FROM "PatBase"
    WHERE pat_id = input_pat_id
      AND EXISTS (
        SELECT 1 FROM jsonb_array_elements(pat_data->'labs') AS elem
        WHERE elem->>'created_at' = new_lab_result->>'created_at'
      )
  ) THEN
    -- Append the new lab result to the labs array
    UPDATE "PatBase"
    SET pat_data = jsonb_set(
      pat_data,
      '{labs}',
      COALESCE(
        pat_data->'labs',
        '[]'::JSONB
      ) || jsonb_build_array(new_lab_result),
      TRUE
    )
    WHERE pat_id = input_pat_id and "userId" = input_userId;
  END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.search_ref_icd(search_term varchar)
RETURNS table(id int8, primary1 text, text text, similarity real)
LANGUAGE plpgsql
AS $$
	begin
		return query
			SELECT b.id, b.primary1, b.text, similarity(search_term, b.conc)
			FROM ref_icd b 
			WHERE search_term % ANY(STRING_TO_ARRAY(b.conc, ' ')) AND b.primary1 != ''
			order by similarity DESC;
	end;
$$;

CREATE OR REPLACE FUNCTION public.search_ref_rx(search_term varchar)
RETURNS table(key int8, ppn int8, count_substances int8, name_strength text, adm_short text, adm_long text, adm_detail text, similarity real)
LANGUAGE plpgsql
AS $$
	begin
		return query
			SELECT b."id", b."ppn", b."count_substances", b."name_strength", b."adm_short", b."adm_long", b."adm_detail", similarity(search_term, b."name_strength")
			FROM ref_rx b 
			WHERE search_term % ANY(STRING_TO_ARRAY(b."name_strength", ' '))
			 order by similarity DESC;
	end;
$$;